export const API_KEY_FILE = './apikey.json';
export const validLanguageIds = {
    "error": "Invalid programming language, must be a valid language ID",
    "available_languages": [
        { id: 13, language: 'Java (.java)' },
        { id: 14, language: 'Python (.py)' },
        { id: 16, language: 'C (.c/.h)' },
        { id: 17, language: 'C/C++ (.cc/.c/.h/.cpp/.hpp)' },
        { id: 18, language: 'C# (.cs)' },
        { id: 20, language: 'Perl (.pl/.sh)' },
        { id: 21, language: 'PHP (.php)' },
        { id: 22, language: 'SQL (.sql)' },
        { id: 23, language: 'VB (.vb/.bas)' },
        { id: 24, language: 'XML (.xml)' },
        { id: 28, language: 'Haskell (.hs/.lhs)' },
        { id: 29, language: 'Pascal (.pas/.inc)' },
        { id: 30, language: 'Go (.go)' },
        { id: 31, language: 'Matlab (.m)' },
        { id: 32, language: 'Lisp (.el)' },
        { id: 33, language: 'Ruby (.rb)' },
        { id: 34, language: 'Assembly (.asm/.s)' },
        { id: 38, language: 'HTML Javascript (.html/.htm/.xhtml)' },
        { id: 39, language: 'Javascript (.js/.ts)' },
        { id: 40, language: 'HTML (.html/.htm/.xhtml)' },
        { id: 41, language: 'Plain text (.txt)' },
        { id: 42, language: 'Text file by char (.txt)' },
        { id: 43, language: 'Swift (.swift)' },
        { id: 44, language: 'Kotlin (.kt/.kts)' },
        { id: 45, language: 'Yacc (.y,.yy,.ypp,.yxx)' },
        { id: 46, language: 'Lex (.l,.ll)' },
        { id: 47, language: 'Elixir (.ex, .exs)' },
        { id: 48, language: 'Python Jupyter Notebook (.ipynb)' },
        { id: 49, language: 'Dart (.dart)' },
        { id: 50, language: 'Shell (.sh/.bash)' },
        { id: 51, language: 'Rust (.rs)' },
        { id: 52, language: 'Scala (.scala)' },
        { id: 53, language: 'R (.r)' },
        { id: 54, language: 'Objective-C (.m, .mm)' },
        { id: 55, language: 'TypeScript (.ts, .tsx)' },
        { id: 56, language: 'Markdown (.md)' },
        { id: 57, language: 'Julia (.jl)' },
        { id: 58, language: 'Groovy (.groovy)' },
        { id: 59, language: 'Sass/SCSS (.scss, .sass)' },
        { id: 60, language: 'CoffeeScript (.coffee)' },
        { id: 61, language: 'Lua (.lua)' },
        { id: 62, language: 'Erlang (.erl, .hrl)' },
        { id: 63, language: 'F# (.fs, .fsi, .fsx)' },
        { id: 64, language: 'Fortran (.f90, .f95)' },
        { id: 65, language: 'Haxe (.hx)' },
        { id: 66, language: 'Scheme (.scm, .ss)' },
        { id: 67, language: 'Tcl (.tcl)' },
        { id: 68, language: 'Ada (.adb, .ads)' },
        { id: 69, language: 'COBOL (.cob, .cbl)' },
        { id: 70, language: 'VHDL (.vhd, .vhdl)' }
    ]
}